1. Write a function so that the columns of the output matrix are powers of the input
vector.<br><br>
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.<br><br>
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [9]:
x = np.array([1, 2, 3, 5])
n = 3
np.vander(x, n)             # inbuilt function

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [14]:
x = np.array([1, 2, 3, 5])                   # with increasing parameter set to True
np.vander(x, increasing=True)      


array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

In [10]:
np.column_stack([x**(n-1-i) for i in range(n)])    # General method    

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]], dtype=int32)

2. Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:<br><br>
The moving average sequence has n-k+1 elements as shown below.<br><br>
The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10 <br>
===== == == == == == == == == == == <br>
Input 10 20 30 40 50 60 70 80 90 100 <br>
y1 25 = (10+20+30+40)/4 <br>
y2 35 = (20+30+40+50)/4 <br>
y3 45 = (30+40+50+60)/4 <br>
y4 55 = (40+50+60+70)/4 <br>
y5 65 = (50+60+70+80)/4 <br>
y6 75 = (60+70+80+90)/4 <br>
y7 85 = (70+80+90+100)/4 <br>
Thus, the moving average sequence has n-k+1=10-4+1=7 values.<br><br>
Question: Write a function to find moving average in an array over a window:<br>
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [16]:
import numpy as np
def moving_average(a, n) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n


a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
n = 3
moving_average(a,n)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])